"""
tools/slack.py
Slack posting tools. Every crew that communicates uses these.
Requires SLACK_BOT_TOKEN in environment.
Channel names come from shared.config.context.SLACK.
"""

import os, json, requests
from datetime import date
from crewai.tools import tool
from shared.config.context import SLACK

def _api(channel: str, text: str, blocks=None) -> dict:
    body = {"channel": channel, "text": text}
    if blocks:
        body["blocks"] = blocks
    r = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={
            "Authorization": f"Bearer {os.environ.get('SLACK_BOT_TOKEN', '')}",
            "Content-Type": "application/json",
        },
        json=body,
    )
    return r.json()

PE = {"urgent": "P0", "high": "P1", "normal": "P2", "low": "P3", "none": "--"}
HS = lambda pct: "GREEN" if pct >= 80 else ("YELLOW" if pct >= 60 else "RED")

def _hdr(t): return {"type": "header", "text": {"type": "plain_text", "text": t}}
def _sec(t): return {"type": "section", "text": {"type": "mrkdwn", "text": t}}
def _div():  return {"type": "divider"}
def _ctx(t): return {"type": "context", "elements": [{"type": "mrkdwn", "text": t}]}


@tool("Post to Slack Channel")
def post(channel: str, message: str) -> str:
    """
    Posts a plain mrkdwn message to any Slack channel.
    Use for quick notifications that don't need structured blocks.
    """
    r = _api(channel, message)
    return json.dumps({"ok": r.get("ok"), "ts": r.get("ts")})


@tool("Post Daily Standup to Slack")
def post_standup(executive_summary: str, done: str, in_progress: str,
                 blocked: str, pending: str, attention: str, meeting_mode: str) -> str:
    """
    Posts the structured daily sprint digest to #pm-standup.
    Template is enforced — just pass the content for each section.
    Do NOT add separators or headers — the tool handles formatting.

    executive_summary: 3-4 bullet points (sprint health, progress, risks)
    done: bullet list of completed items (or 'None')
    in_progress: bullet list of active items with assignee and SP
    blocked: bullet list of blocked items with reason
    pending: bullet list of not-started items with assignee and SP
    attention: stale PRs, CI failures, stale tasks
    meeting_mode: either 'STANDUP: X blockers. 15-min focused session.'
                  or 'OPEN SLOT: No blockers. Available for strategic discussion.'
    """
    today = date.today().strftime("%B %d, %Y")
    r = _api(SLACK["standup"], f"Sprint Digest {today}", [
        _hdr(f"📊 Sprint Digest — {today}"),
        _sec(f"*Executive Summary*\n{executive_summary}"),
        _div(),
        _sec(
            f"*✅ Done*\n{done or '_None_'}\n\n"
            f"*🔄 In Progress*\n{in_progress or '_None_'}\n\n"
            f"*🚫 Blocked*\n{blocked or '_None_'}\n\n"
            f"*⏳ Pending*\n{pending or '_None_'}"
        ),
        _div(),
        _sec(f"*⚠️ Needs Attention*\n{attention or '_All clear_'}"),
        _div(),
        _sec(f"*🎯 Meeting Mode*\n{meeting_mode}"),
        _ctx("_Posted by CareSpace PM AI_"),
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Sprint Plan to Slack")
def post_sprint_plan(sprint_name: str, tasks_json: str, total_sp: int) -> str:
    """
    Posts the sprint planning results to #pm-sprint-board.
    sprint_name: e.g. 'Sprint 7 -- Apr 13-Apr 27'
    tasks_json: JSON array of {name, priority, assignee, story_points}
    total_sp: total story points committed
    """
    tasks = json.loads(tasks_json)
    lines = [
        f"{PE.get(t.get('priority', 'none'), '--')} *{t['name']}*"
        + (f"  ->  _{t.get('assignee', 'unassigned')}_" if t.get("assignee") else "  ->  _(unassigned)_")
        + (f"  `{t.get('story_points', '?')} SP`" if t.get("story_points") else "")
        for t in tasks
    ]
    r = _api(SLACK["sprint"], f"Sprint plan: {sprint_name}", [
        _hdr(sprint_name),
        _sec(f"*{len(tasks)} tasks committed - {total_sp} story points*"),
        _div(),
        _sec("\n".join(lines) or "_No tasks selected_"),
        _ctx("_Sprint plan generated by CareSpace PM AI_"),
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Blocker Alert to Slack")
def post_blocker(description: str, task_url: str, owner: str, impact: str = "") -> str:
    """
    Posts an urgent blocker notification to #pm-alerts.
    Call once per blocker. impact: what business outcome is blocked (optional).
    """
    body = f"*BLOCKER* -- {description}\n*Owner:* {owner}\n*Task:* {task_url}"
    if impact:
        body += f"\n*Business Impact:* {impact}"
    r = _api(SLACK["alerts"], f"BLOCKER: {description[:60]}", [_sec(body)])
    return json.dumps({"ok": r.get("ok")})


@tool("Post SLA Breach Alert to Slack")
def post_sla_breach(bug_name: str, task_url: str, priority: str, hours_open: int) -> str:
    """
    Posts an SLA breach alert to #pm-alerts for bugs that exceeded their resolution window.
    """
    sla = {"urgent": 4, "high": 24, "normal": 72, "low": 168}.get(priority, 24)
    r = _api(SLACK["alerts"], f"SLA BREACH: {bug_name}", [
        _sec(
            f"*SLA BREACH* -- {priority.upper()} bug open *{hours_open}h* (SLA: {sla}h)\n"
            f"*Bug:* {bug_name}\n*Task:* {task_url}"
        )
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Sprint Retrospective to Slack")
def post_retro(sprint_name: str, completion_pct: float,
               velocity_sp: int, carry_over: int, doc_url: str) -> str:
    """Posts end-of-sprint retrospective summary to #pm-sprint-board."""
    r = _api(SLACK["sprint"], f"Retro: {sprint_name}", [
        _hdr(f"{HS(completion_pct)} {sprint_name} -- Retrospective"),
        _sec(
            f"Completion: *{completion_pct}%*  -  "
            f"Velocity: *{velocity_sp} SP*  -  "
            f"Carry-over: *{carry_over} tasks*"
        ),
        _sec(f"Full report: {doc_url}"),
        _ctx("_Retrospective by CareSpace PM AI_"),
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post GTM Intelligence to Slack")
def post_gtm(headline: str, deals_at_risk: int, pipeline_value: str,
             gaps: str, actions: str) -> str:
    """Posts the weekly GTM pipeline intelligence report to #pm-gtm."""
    r = _api(SLACK["gtm"], "GTM Pipeline Update", [
        _hdr("GTM Pipeline Intelligence"),
        _sec(headline),
        _sec(f"*Deals at risk:* {deals_at_risk}  -  *Pipeline value:* {pipeline_value}"),
        _div(),
        _sec(f"*Coverage gaps:*\n{gaps or '_None detected_'}"),
        _sec(f"*Recommended actions:*\n{actions}"),
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Executive Report to Slack")
def post_exec(report_summary: str) -> str:
    """Posts the weekly cross-workspace executive summary to #pm-exec-updates."""
    r = _api(SLACK["exec"], "Weekly Status Report", [
        _hdr(f"CareSpace Weekly Status -- {date.today().strftime('%B %d, %Y')}"),
        _sec(report_summary),
        _ctx("_Generated by CareSpace PM AI_"),
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Compliance Alert to Slack")
def post_compliance(control_name: str, severity: str, finding: str) -> str:
    """Posts a compliance control gap or failure alert to #pm-compliance."""
    r = _api(SLACK["compliance"], f"Compliance: {control_name}", [
        _sec(
            f"*COMPLIANCE {severity.upper()}*\n"
            f"*Control:* {control_name}\n"
            f"*Finding:* {finding}"
        )
    ])
    return json.dumps({"ok": r.get("ok")})


@tool("Post Customer Success Alert to Slack")
def post_cs_alert(account_name: str, risk_type: str, detail: str) -> str:
    """Posts a customer success risk alert to #pm-customer-success."""
    r = _api(SLACK["cs"], f"CS Alert: {account_name}", [
        _sec(f"*CS RISK -- {account_name}*\n*Type:* {risk_type}\n*Detail:* {detail}")
    ])
    return json.dumps({"ok": r.get("ok")})
